insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (29, 9, '成员管理', 'STQ#CYGL_URL', null, null, '28_STQ', '1000', null, null, null, '16', '', '', '', '', '', null, null, null, 16, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (26, 9, '本地手输专线（手输资费）', '本地手输专线（手输资费）', null, null, '25_DD', '1100', null, null, null, '13', '查询白名单限制', '', '', '', '', null, null, null, 13, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (25, 9, '合同收集', '合同收集', null, null, '22_DD', '1000', null, null, null, '12', '查询白名单限制', '', '', '', '', null, null, null, 12, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (24, 9, '欠费回收', '欠费回收', null, null, '24_DD', '1100', null, null, null, '11', '查询白名单限制', '', '', '', '', null, null, null, 11, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (23, 9, '添加V网成员', '添加V网成员', null, null, '1000_VW', '1100', null, null, null, '7', '查询白名单限制', '', '', '', '', null, null, null, 7, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (22, 9, '酒店宽带', '酒店宽带', null, null, '18_DD', '1100', null, null, null, '6', '查询白名单限制', '', '', '', '', null, null, null, 6, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (21, 9, 'MAS短流程', 'MAS短流程', null, null, '17_DD', '1000', null, null, null, '5', '查询白名单限制', '', '', '', '', null, null, null, 5, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (20, 9, '数据专线（本地MPLS-VPN）', '数据专线（本地MPLS-VPN）', null, null, '9_DD', '1100', null, null, null, '4', '查询白名单限制', '', '', '', '', null, null, null, 4, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (19, 9, '互联网专线', '互联网专线', null, null, '8_DD', '1100', null, null, null, '3', '查询白名单限制', '', '', '', '', null, null, null, 3, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (32, 9, '实名资料变更', '实名资料变更', null, null, '33_DD', '1100', null, null, null, '19', '查询白名单限制', '', '', '', '', null, null, null, 9, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (28, 8, '云网融合', 'STQ#YWRH_URL', null, null, '27_STQ', '1100', null, null, null, '15', '查询白名单限制', '', '', '', '', null, null, null, 15, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (30, 8, '和飞速云网版', 'STQ#HFSYWB_URL', null, null, '29_STQ', '1000', null, null, null, '17', '查询白名单限制', '', '', '', '', null, null, null, 17, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (27, 8, '和飞速（仅办理专线6611）', '和飞速（仅办理专线6611）', null, null, '26_DD', '1000', null, null, null, '14', '查询白名单限制', '', '', '', '', null, null, null, 14, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (17, 8, '和飞速融合办理', '和飞速融合办理', null, null, '10_DD', '1000', null, null, null, '1', '', '', '', '', '', null, null, null, 1, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (34, 1, '云产品', 'STQ#YKJ_URL', null, null, '33_STQ', '1000', null, null, null, '21', '', '', '', '', '', null, null, null, 21, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (56, 1, '云专线', 'STQ#YZW_URL', null, null, '34_STQ', '1000', null, null, null, '22', '', '', '', '', '', null, null, null, 22, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (31, 1, '省内云', 'STQ#SNY_URL', null, null, '30_STQ', '1000', null, null, null, '18', '查询白名单限制', '', '', '', '', null, null, null, 18, null, '', '');

insert into attr_value (ATTR_VALUE_ID, ATTR_ID, ATTR_VALUE_NAME, ATTR_VALUE_DESC, CREATE_DATE, STATUS_DATE, ATTR_VALUE, STATUS_CD, UPDATE_DATE, CREATE_STAFF, UPDATE_STAFF, ATTR_VALUE_SORT, REMARK, EXT_ATTR_VALUE_ID, ATTR_DESC, ATTR_VALUE_CODE, HB_ATTR_VALUE, OPER_REGION_ID, PARTY_ID, PARTY_ROLE_ID, SEQ, SORTBY, VALUE_NUMBER, ATTR_VALUE_CD)
values (33, 1, '云主机', 'STQ#YZJ_URL', null, null, '32_STQ', '1000', null, null, null, '20', '', '', '', '', '', null, null, null, 20, null, '', '');

